// <auto-generated />
using System;
using DbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbConnection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250119151255_mg-06")]
    partial class mg06
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbEntities.Applicant", b =>
                {
                    b.Property<int>("ApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<short?>("EnglishLanguageLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int");

                    b.HasKey("ApplicantId");

                    b.HasIndex("CityId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("DbEntities.Applicant_JobAnnouncement", b =>
                {
                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int");

                    b.Property<int?>("Applicant_JobAnnouncementApplicantId")
                        .HasColumnType("int");

                    b.Property<int?>("Applicant_JobAnnouncementJobAnnouncementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicantId", "JobAnnouncementId");

                    b.HasIndex("JobAnnouncementId");

                    b.HasIndex("Applicant_JobAnnouncementApplicantId", "Applicant_JobAnnouncementJobAnnouncementId");

                    b.ToTable("Applicant_JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("DbEntities.CommissionRule", b =>
                {
                    b.Property<int>("CommissionRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<short>("CommissionBasedOn")
                        .HasColumnType("smallint");

                    b.Property<short>("CommissionType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("MaximumAmount")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumNumber")
                        .HasColumnType("int");

                    b.Property<long?>("MinimumAmount")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinimumNumber")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("CommissionRuleId");

                    b.ToTable("CommissionRule");
                });

            modelBuilder.Entity("DbEntities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("DbEntities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OTPExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement", b =>
                {
                    b.Property<int>("JobAnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEmploymentExam")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ShowCompanyInfo")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobAnnouncementId");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncementCategory", b =>
                {
                    b.Property<int>("JobAnnouncementCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobAnnouncementCategoryId");

                    b.ToTable("JobAnnouncementCategory");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_JobAnnouncementCategory", b =>
                {
                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int");

                    b.Property<int>("JobAnnouncementCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("JobAnnouncementId", "JobAnnouncementCategoryId");

                    b.HasIndex("JobAnnouncementCategoryId");

                    b.ToTable("JobAnnouncement_JobAnnouncementCategory");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_Skill", b =>
                {
                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegistrationAmount")
                        .HasColumnType("int");

                    b.HasKey("JobAnnouncementId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobAnnouncement_Skill");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_StudyField", b =>
                {
                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int");

                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("JobAnnouncementId", "StudyFieldId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("JobAnnouncement_StudyField");
                });

            modelBuilder.Entity("DbEntities.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentType");

                    b.HasData(
                        new
                        {
                            PaymentTypeId = 1,
                            PaymentTypeName = "پرداخت آنلاین"
                        },
                        new
                        {
                            PaymentTypeId = 2,
                            PaymentTypeName = "پرداخت کارت به کارت"
                        },
                        new
                        {
                            PaymentTypeId = 3,
                            PaymentTypeName = "پرداخت از اعتبار کیف پول"
                        });
                });

            modelBuilder.Entity("DbEntities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("DbEntities.ReferralCode", b =>
                {
                    b.Property<int>("ReferralCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReferralCodeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReferralCodeId");

                    b.ToTable("ReferralCode");
                });

            modelBuilder.Entity("DbEntities.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("SettingId");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("DbEntities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkillId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("DbEntities.StudyField", b =>
                {
                    b.Property<int>("StudyFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("StudyFieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudyFieldId");

                    b.ToTable("StudyField");
                });

            modelBuilder.Entity("DbEntities.SystemSMS", b =>
                {
                    b.Property<int>("SystemSMSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<short>("SMSType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SystemSMSId");

                    b.ToTable("SystemSMS");
                });

            modelBuilder.Entity("DbEntities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WalletId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("DbEntities.WalletCommission", b =>
                {
                    b.Property<int>("WalletCommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Commission")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("WalletCommissionId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletCommission");
                });

            modelBuilder.Entity("DbEntities.Wallet_ReferralCode_CommissionRule", b =>
                {
                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<int>("ReferralCodeId")
                        .HasColumnType("int");

                    b.Property<int>("CommissionRuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WalletId", "ReferralCodeId", "CommissionRuleId");

                    b.HasIndex("CommissionRuleId");

                    b.HasIndex("ReferralCodeId");

                    b.ToTable("Wallet_ReferralCode_CommissionRule");
                });

            modelBuilder.Entity("DbEntities.Applicant", b =>
                {
                    b.HasOne("DbEntities.City", "City")
                        .WithMany("ApplicantList")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.StudyField", "StudyField")
                        .WithMany("ApplicantList")
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("DbEntities.Applicant_JobAnnouncement", b =>
                {
                    b.HasOne("DbEntities.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("Applicant_JobAnnouncement_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Applicant_JobAnnouncement", null)
                        .WithMany("Applicant_JobAnnouncement_List")
                        .HasForeignKey("Applicant_JobAnnouncementApplicantId", "Applicant_JobAnnouncementJobAnnouncementId");

                    b.Navigation("Applicant");

                    b.Navigation("JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.City", b =>
                {
                    b.HasOne("DbEntities.Province", "Province")
                        .WithMany("CityList")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomRoleClaim", b =>
                {
                    b.HasOne("DbEntities.Identity.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserClaim", b =>
                {
                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserLogin", b =>
                {
                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserRole", b =>
                {
                    b.HasOne("DbEntities.Identity.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserToken", b =>
                {
                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement", b =>
                {
                    b.HasOne("DbEntities.Company", "Company")
                        .WithMany("JobAnnouncementList")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_JobAnnouncementCategory", b =>
                {
                    b.HasOne("DbEntities.JobAnnouncementCategory", "JobAnnouncementCategory")
                        .WithMany("JobAnnouncement_JobAnnouncementCategory_List")
                        .HasForeignKey("JobAnnouncementCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_JobAnnouncementCategory_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAnnouncement");

                    b.Navigation("JobAnnouncementCategory");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_Skill", b =>
                {
                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_Skill_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Skill", "Skill")
                        .WithMany("JobAnnouncement_Skill_List")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAnnouncement");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_StudyField", b =>
                {
                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_StudyField_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.StudyField", "StudyField")
                        .WithMany("JobAnnouncement_StudyField_List")
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAnnouncement");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("DbEntities.WalletCommission", b =>
                {
                    b.HasOne("DbEntities.Wallet", "Wallet")
                        .WithMany("WalletCommissionList")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DbEntities.Wallet_ReferralCode_CommissionRule", b =>
                {
                    b.HasOne("DbEntities.CommissionRule", "CommissionRule")
                        .WithMany("Wallet_ReferralCode_CommissionRule_List")
                        .HasForeignKey("CommissionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.ReferralCode", "ReferralCode")
                        .WithMany("Wallet_ReferralCode_CommissionRule_List")
                        .HasForeignKey("ReferralCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Wallet", "Wallet")
                        .WithMany("Wallet_ReferralCode_CommissionRule_List")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionRule");

                    b.Navigation("ReferralCode");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DbEntities.Applicant_JobAnnouncement", b =>
                {
                    b.Navigation("Applicant_JobAnnouncement_List");
                });

            modelBuilder.Entity("DbEntities.City", b =>
                {
                    b.Navigation("ApplicantList");
                });

            modelBuilder.Entity("DbEntities.CommissionRule", b =>
                {
                    b.Navigation("Wallet_ReferralCode_CommissionRule_List");
                });

            modelBuilder.Entity("DbEntities.Company", b =>
                {
                    b.Navigation("JobAnnouncementList");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement", b =>
                {
                    b.Navigation("Applicant_JobAnnouncement_List");

                    b.Navigation("JobAnnouncement_JobAnnouncementCategory_List");

                    b.Navigation("JobAnnouncement_Skill_List");

                    b.Navigation("JobAnnouncement_StudyField_List");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncementCategory", b =>
                {
                    b.Navigation("JobAnnouncement_JobAnnouncementCategory_List");
                });

            modelBuilder.Entity("DbEntities.Province", b =>
                {
                    b.Navigation("CityList");
                });

            modelBuilder.Entity("DbEntities.ReferralCode", b =>
                {
                    b.Navigation("Wallet_ReferralCode_CommissionRule_List");
                });

            modelBuilder.Entity("DbEntities.Skill", b =>
                {
                    b.Navigation("JobAnnouncement_Skill_List");
                });

            modelBuilder.Entity("DbEntities.StudyField", b =>
                {
                    b.Navigation("ApplicantList");

                    b.Navigation("JobAnnouncement_StudyField_List");
                });

            modelBuilder.Entity("DbEntities.Wallet", b =>
                {
                    b.Navigation("Wallet_ReferralCode_CommissionRule_List");

                    b.Navigation("WalletCommissionList");
                });
#pragma warning restore 612, 618
        }
    }
}
