// <auto-generated />
using System;
using DbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbConnection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207102942_mg-12")]
    partial class mg12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbEntities.Applicant", b =>
                {
                    b.Property<int>("ApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantId"));

                    b.Property<string>("Address")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("EducationalCertificateFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("EnglishLanguageLevel")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("IdentityCertificateFirstPageFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityCertificateSecondPageFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("NationalCardBackFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCardFrontFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonalImageFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("StudyFieldId")
                        .HasColumnType("int");

                    b.HasKey("ApplicantId");

                    b.HasIndex("CityId");

                    b.HasIndex("StudyFieldId");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("DbEntities.ApplicantExamAttempt", b =>
                {
                    b.Property<int>("ApplicantExamAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantExamAttemptId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("QuestionsOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("ApplicantExamAttemptId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ExamId");

                    b.ToTable("ApplicantExamAttempt");
                });

            modelBuilder.Entity("DbEntities.ApplicantExamQuestionAnswer", b =>
                {
                    b.Property<int>("ExamQuestionId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ApplicantExamAttemptId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("AdditionalCorrectionTips")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ExamQuestionOptionId")
                        .HasColumnType("int");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamQuestionId", "ApplicantExamAttemptId");

                    b.HasIndex("ApplicantExamAttemptId");

                    b.HasIndex("ExamQuestionOptionId");

                    b.ToTable("ApplicantExamQuestionAnswer");
                });

            modelBuilder.Entity("DbEntities.Applicant_JobAnnouncement", b =>
                {
                    b.Property<int>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ApplicantId", "JobAnnouncementId");

                    b.HasIndex("JobAnnouncementId");

                    b.ToTable("Applicant_JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("DbEntities.Collaborator", b =>
                {
                    b.Property<int>("CollaboratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollaboratorId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("CollaboratorId");

                    b.ToTable("Collaborator");
                });

            modelBuilder.Entity("DbEntities.CommissionRule", b =>
                {
                    b.Property<int>("CommissionRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommissionRuleId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<short>("CommissionBasedOn")
                        .HasColumnType("smallint");

                    b.Property<short>("CommissionType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("MaximumAmount")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaximumNumber")
                        .HasColumnType("int");

                    b.Property<long?>("MinimumAmount")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinimumNumber")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("CommissionRuleId");

                    b.ToTable("CommissionRule");
                });

            modelBuilder.Entity("DbEntities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyLogoFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("WebsiteAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("DbEntities.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExamId");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("DbEntities.ExamQuestion", b =>
                {
                    b.Property<int>("ExamQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamQuestionId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<double>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("ExamQuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestion");
                });

            modelBuilder.Entity("DbEntities.ExamQuestionOption", b =>
                {
                    b.Property<int>("ExamQuestionOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamQuestionOptionId"));

                    b.Property<int>("ExamQuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExamQuestionOptionId");

                    b.HasIndex("ExamQuestionId");

                    b.ToTable("ExamQuestionOption");
                });

            modelBuilder.Entity("DbEntities.ExamResource", b =>
                {
                    b.Property<int>("ExamResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamResourceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DownloadLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("ExamResourceId");

                    b.ToTable("ExamResource");
                });

            modelBuilder.Entity("DbEntities.ExamResourceOrder", b =>
                {
                    b.Property<int>("ExamResourceOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamResourceOrderId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamResourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExamResourceOrderId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ExamResourceId");

                    b.ToTable("ExamResourceOrder");
                });

            modelBuilder.Entity("DbEntities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OTPExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DbEntities.Identity.CustomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DbEntities.Identity.CustomRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim", (string)null);
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim", (string)null);
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", (string)null);
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("DbEntities.InterviewAppointment", b =>
                {
                    b.Property<int>("InterviewAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewAppointmentId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("InterviewAppointmentId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("JobAnnouncementId");

                    b.ToTable("InterviewAppointment");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement", b =>
                {
                    b.Property<int>("JobAnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobAnnouncementId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEmploymentExam")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JobAnnouncementApplicationDeadlineDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("JobAnnouncementApplicationDeadlineDateTo")
                        .HasColumnType("datetime2");

                    b.Property<short?>("JobTimeType")
                        .HasColumnType("smallint");

                    b.Property<short?>("JobType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShamsiJobAnnouncementApplicationDeadlineDateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShamsiJobAnnouncementApplicationDeadlineDateTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShowCompanyInfo")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JobAnnouncementId");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncementCategory", b =>
                {
                    b.Property<int>("JobAnnouncementCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobAnnouncementCategoryId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobAnnouncementCategoryId");

                    b.ToTable("JobAnnouncementCategory");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<bool>("AllowNavigateToPreviousQuestion")
                        .HasColumnType("bit");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RandomizeOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("RandomizeQuestions")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamId", "JobAnnouncementId");

                    b.HasIndex("JobAnnouncementId");

                    b.ToTable("JobAnnouncement_Exam");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_ExamResource", b =>
                {
                    b.Property<int>("ExamResourceId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExamResourceId", "JobAnnouncementId");

                    b.HasIndex("JobAnnouncementId");

                    b.ToTable("JobAnnouncement_ExamResource");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_JobAnnouncementCategory", b =>
                {
                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("JobAnnouncementCategoryId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("JobAnnouncementId", "JobAnnouncementCategoryId");

                    b.HasIndex("JobAnnouncementCategoryId");

                    b.ToTable("JobAnnouncement_JobAnnouncementCategory");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegistrationAmount")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "JobAnnouncementId");

                    b.HasIndex("JobAnnouncementId");

                    b.ToTable("JobAnnouncement_Skill");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_StudyField", b =>
                {
                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("JobAnnouncementId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudyFieldId", "JobAnnouncementId");

                    b.HasIndex("JobAnnouncementId");

                    b.ToTable("JobAnnouncement_StudyField");
                });

            modelBuilder.Entity("DbEntities.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentType");

                    b.HasData(
                        new
                        {
                            PaymentTypeId = 1,
                            PaymentTypeName = "پرداخت آنلاین"
                        },
                        new
                        {
                            PaymentTypeId = 2,
                            PaymentTypeName = "پرداخت کارت به کارت"
                        },
                        new
                        {
                            PaymentTypeId = 3,
                            PaymentTypeName = "پرداخت از اعتبار کیف پول"
                        });
                });

            modelBuilder.Entity("DbEntities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("DbEntities.SMSPattern", b =>
                {
                    b.Property<int>("SMSPatternId")
                        .HasColumnType("int");

                    b.Property<string>("PatternCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SMSPatternName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SMSPatternId");

                    b.ToTable("SMSPattern");
                });

            modelBuilder.Entity("DbEntities.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SettingValue")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("SettingId");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("DbEntities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkillId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("DbEntities.Skill_ExamResource", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ExamResourceId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SkillId", "ExamResourceId");

                    b.HasIndex("ExamResourceId");

                    b.ToTable("Skill_ExamResource");
                });

            modelBuilder.Entity("DbEntities.StudyField", b =>
                {
                    b.Property<int>("StudyFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudyFieldId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("StudyFieldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudyFieldId");

                    b.ToTable("StudyField");
                });

            modelBuilder.Entity("DbEntities.StudyField_ExamResource", b =>
                {
                    b.Property<int>("StudyFieldId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("ExamResourceId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudyFieldId", "ExamResourceId");

                    b.HasIndex("ExamResourceId");

                    b.ToTable("StudyField_ExamResource");
                });

            modelBuilder.Entity("DbEntities.SystemSMS", b =>
                {
                    b.Property<int>("SystemSMSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemSMSId"));

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<short>("SMSType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SystemSMSId");

                    b.ToTable("SystemSMS");
                });

            modelBuilder.Entity("DbEntities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WalletId");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("DbEntities.WalletCommission", b =>
                {
                    b.Property<int>("WalletCommissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletCommissionId"));

                    b.Property<int>("Commission")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("WalletCommissionId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletCommission");
                });

            modelBuilder.Entity("DbEntities.Wallet_Collaborator_CommissionRule", b =>
                {
                    b.Property<int>("WalletId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CollaboratorId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("CommissionRuleId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WalletId", "CollaboratorId", "CommissionRuleId");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("CommissionRuleId");

                    b.ToTable("Wallet_Collaborator_CommissionRule");
                });

            modelBuilder.Entity("DbEntities.Applicant", b =>
                {
                    b.HasOne("DbEntities.City", "City")
                        .WithMany("ApplicantList")
                        .HasForeignKey("CityId");

                    b.HasOne("DbEntities.StudyField", "StudyField")
                        .WithMany("ApplicantList")
                        .HasForeignKey("StudyFieldId");

                    b.Navigation("City");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("DbEntities.ApplicantExamAttempt", b =>
                {
                    b.HasOne("DbEntities.Applicant", "Applicant")
                        .WithMany("ApplicantExamAttempt")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Exam", "Exam")
                        .WithMany("ApplicantAttemptList")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("DbEntities.ApplicantExamQuestionAnswer", b =>
                {
                    b.HasOne("DbEntities.ApplicantExamAttempt", "ApplicantExamAttempt")
                        .WithMany("ApplicantExamQuestionAnswerList")
                        .HasForeignKey("ApplicantExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.ExamQuestion", "ExamQuestion")
                        .WithMany("ApplicantExamQuestionAnswerList")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DbEntities.ExamQuestionOption", "ExamQuestionOption")
                        .WithMany("ApplicantExamQuestionAnswerList")
                        .HasForeignKey("ExamQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicantExamAttempt");

                    b.Navigation("ExamQuestion");

                    b.Navigation("ExamQuestionOption");
                });

            modelBuilder.Entity("DbEntities.Applicant_JobAnnouncement", b =>
                {
                    b.HasOne("DbEntities.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("Applicant_JobAnnouncement_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.City", b =>
                {
                    b.HasOne("DbEntities.Province", "Province")
                        .WithMany("CityList")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("DbEntities.ExamQuestion", b =>
                {
                    b.HasOne("DbEntities.Exam", "Exam")
                        .WithMany("ExamQuestionList")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("DbEntities.ExamQuestionOption", b =>
                {
                    b.HasOne("DbEntities.ExamQuestion", "ExamQuestion")
                        .WithMany("ExamQuestionOptionList")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("DbEntities.ExamResourceOrder", b =>
                {
                    b.HasOne("DbEntities.Applicant", "Applicant")
                        .WithMany("ExamResourceOrderList")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.ExamResource", "ExamResource")
                        .WithMany("ExamResourceOrderList")
                        .HasForeignKey("ExamResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("ExamResource");
                });

            modelBuilder.Entity("DbEntities.Identity.CustomRoleClaim", b =>
                {
                    b.HasOne("DbEntities.Identity.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserClaim", b =>
                {
                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserLogin", b =>
                {
                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserRole", b =>
                {
                    b.HasOne("DbEntities.Identity.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.Identity.CustomUserToken", b =>
                {
                    b.HasOne("DbEntities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbEntities.InterviewAppointment", b =>
                {
                    b.HasOne("DbEntities.Applicant", "Applicant")
                        .WithMany("InterviewAppointmentList")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("InterviewAppointmentList")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement", b =>
                {
                    b.HasOne("DbEntities.City", "City")
                        .WithMany("JobAnnouncementList")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Company", "Company")
                        .WithMany("JobAnnouncementList")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_Exam", b =>
                {
                    b.HasOne("DbEntities.Exam", "Exam")
                        .WithMany("JobAnnouncement_Exam_List")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_Exam_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_ExamResource", b =>
                {
                    b.HasOne("DbEntities.ExamResource", "ExamResource")
                        .WithMany("JobAnnouncement_ExamResource_List")
                        .HasForeignKey("ExamResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_ExamResource_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamResource");

                    b.Navigation("JobAnnouncement");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_JobAnnouncementCategory", b =>
                {
                    b.HasOne("DbEntities.JobAnnouncementCategory", "JobAnnouncementCategory")
                        .WithMany("JobAnnouncement_JobAnnouncementCategory_List")
                        .HasForeignKey("JobAnnouncementCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_JobAnnouncementCategory_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAnnouncement");

                    b.Navigation("JobAnnouncementCategory");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_Skill", b =>
                {
                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_Skill_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Skill", "Skill")
                        .WithMany("JobAnnouncement_Skill_List")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAnnouncement");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement_StudyField", b =>
                {
                    b.HasOne("DbEntities.JobAnnouncement", "JobAnnouncement")
                        .WithMany("JobAnnouncement_StudyField_List")
                        .HasForeignKey("JobAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.StudyField", "StudyField")
                        .WithMany("JobAnnouncement_StudyField_List")
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobAnnouncement");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("DbEntities.Skill_ExamResource", b =>
                {
                    b.HasOne("DbEntities.ExamResource", "ExamResource")
                        .WithMany("Skill_ExamResource_List")
                        .HasForeignKey("ExamResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Skill", "Skill")
                        .WithMany("Skill_ExamResource_List")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamResource");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DbEntities.StudyField_ExamResource", b =>
                {
                    b.HasOne("DbEntities.ExamResource", "ExamResource")
                        .WithMany("StudyField_ExamResource_List")
                        .HasForeignKey("ExamResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.StudyField", "StudyField")
                        .WithMany("StudyField_ExamResource_List")
                        .HasForeignKey("StudyFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamResource");

                    b.Navigation("StudyField");
                });

            modelBuilder.Entity("DbEntities.WalletCommission", b =>
                {
                    b.HasOne("DbEntities.Wallet", "Wallet")
                        .WithMany("WalletCommissionList")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DbEntities.Wallet_Collaborator_CommissionRule", b =>
                {
                    b.HasOne("DbEntities.Collaborator", "Collaborator")
                        .WithMany("Wallet_Collaborator_CommissionRule_List")
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.CommissionRule", "CommissionRule")
                        .WithMany("Wallet_Collaborator_CommissionRule_List")
                        .HasForeignKey("CommissionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbEntities.Wallet", "Wallet")
                        .WithMany("Wallet_Collaborator_CommissionRule_List")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("CommissionRule");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("DbEntities.Applicant", b =>
                {
                    b.Navigation("ApplicantExamAttempt");

                    b.Navigation("ExamResourceOrderList");

                    b.Navigation("InterviewAppointmentList");
                });

            modelBuilder.Entity("DbEntities.ApplicantExamAttempt", b =>
                {
                    b.Navigation("ApplicantExamQuestionAnswerList");
                });

            modelBuilder.Entity("DbEntities.City", b =>
                {
                    b.Navigation("ApplicantList");

                    b.Navigation("JobAnnouncementList");
                });

            modelBuilder.Entity("DbEntities.Collaborator", b =>
                {
                    b.Navigation("Wallet_Collaborator_CommissionRule_List");
                });

            modelBuilder.Entity("DbEntities.CommissionRule", b =>
                {
                    b.Navigation("Wallet_Collaborator_CommissionRule_List");
                });

            modelBuilder.Entity("DbEntities.Company", b =>
                {
                    b.Navigation("JobAnnouncementList");
                });

            modelBuilder.Entity("DbEntities.Exam", b =>
                {
                    b.Navigation("ApplicantAttemptList");

                    b.Navigation("ExamQuestionList");

                    b.Navigation("JobAnnouncement_Exam_List");
                });

            modelBuilder.Entity("DbEntities.ExamQuestion", b =>
                {
                    b.Navigation("ApplicantExamQuestionAnswerList");

                    b.Navigation("ExamQuestionOptionList");
                });

            modelBuilder.Entity("DbEntities.ExamQuestionOption", b =>
                {
                    b.Navigation("ApplicantExamQuestionAnswerList");
                });

            modelBuilder.Entity("DbEntities.ExamResource", b =>
                {
                    b.Navigation("ExamResourceOrderList");

                    b.Navigation("JobAnnouncement_ExamResource_List");

                    b.Navigation("Skill_ExamResource_List");

                    b.Navigation("StudyField_ExamResource_List");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncement", b =>
                {
                    b.Navigation("Applicant_JobAnnouncement_List");

                    b.Navigation("InterviewAppointmentList");

                    b.Navigation("JobAnnouncement_ExamResource_List");

                    b.Navigation("JobAnnouncement_Exam_List");

                    b.Navigation("JobAnnouncement_JobAnnouncementCategory_List");

                    b.Navigation("JobAnnouncement_Skill_List");

                    b.Navigation("JobAnnouncement_StudyField_List");
                });

            modelBuilder.Entity("DbEntities.JobAnnouncementCategory", b =>
                {
                    b.Navigation("JobAnnouncement_JobAnnouncementCategory_List");
                });

            modelBuilder.Entity("DbEntities.Province", b =>
                {
                    b.Navigation("CityList");
                });

            modelBuilder.Entity("DbEntities.Skill", b =>
                {
                    b.Navigation("JobAnnouncement_Skill_List");

                    b.Navigation("Skill_ExamResource_List");
                });

            modelBuilder.Entity("DbEntities.StudyField", b =>
                {
                    b.Navigation("ApplicantList");

                    b.Navigation("JobAnnouncement_StudyField_List");

                    b.Navigation("StudyField_ExamResource_List");
                });

            modelBuilder.Entity("DbEntities.Wallet", b =>
                {
                    b.Navigation("WalletCommissionList");

                    b.Navigation("Wallet_Collaborator_CommissionRule_List");
                });
#pragma warning restore 612, 618
        }
    }
}
